### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by massiws** [sambindoff/laravel-gust#4]
Can't install on Laravel 8 because this package require PHP-7.4, but Laravel 8 has PHP-7.3.
Are there any dependencies preventing you from setting a minor PHP version?

```json
    "require": {
        "php": "^7.3|^8.0",
        "illuminate/contracts": "^8.0",
```

**Comment by y0rdie** [comment]
Nope nothing should be preventing this, will update it along with a mix 6 release when this gets merged to laravel/laravel. Thanks for reporting.

**Comment by y0rdie** [comment]
This should be resolved with the latest release, again thanks for taking the time to report @massiws
