### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by mauriciovillam** [sambindoff/laravel-gust#6]
Hey Sam!

Thanks for submitting this piece of work to the Laravel community. I would recommend to introduce some unit tests and do some separation of concerns: perhaps the InstallCommand does too much. This package may require changes if any stack changes (fortify, breeze, or ui), so tests will help you a lot to track these issues.

Best of luck!

**Comment by y0rdie** [comment]
Hey Mauricio,

Thanks for taking the time to look at the package and I appreciate your feedback, feel free to submit a PR if you'd like to improve on anything.

All the best,
Sam
